// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALrqJyijTEvmkvFS3Ntj88Ycq6jkWVUx4',
    appId: '1:1006423865511:web:83431d8ce036d0bc5c0382',
    messagingSenderId: '1006423865511',
    projectId: 'hawks-3448f',
    authDomain: 'hawks-3448f.firebaseapp.com',
    storageBucket: 'hawks-3448f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4ULZmKpE8-hW7q_7vumdFDzxidmKbDKY',
    appId: '1:1006423865511:android:eb2da0e4c04a80c85c0382',
    messagingSenderId: '1006423865511',
    projectId: 'hawks-3448f',
    storageBucket: 'hawks-3448f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClrSni0wz9HXq_35ORlqHWEFk74q7HFiw',
    appId: '1:1006423865511:ios:c72d62e44d57bab25c0382',
    messagingSenderId: '1006423865511',
    projectId: 'hawks-3448f',
    storageBucket: 'hawks-3448f.firebasestorage.app',
    iosBundleId: 'com.example.hawks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClrSni0wz9HXq_35ORlqHWEFk74q7HFiw',
    appId: '1:1006423865511:ios:c72d62e44d57bab25c0382',
    messagingSenderId: '1006423865511',
    projectId: 'hawks-3448f',
    storageBucket: 'hawks-3448f.firebasestorage.app',
    iosBundleId: 'com.example.hawks',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALrqJyijTEvmkvFS3Ntj88Ycq6jkWVUx4',
    appId: '1:1006423865511:web:350ecd483a59ab055c0382',
    messagingSenderId: '1006423865511',
    projectId: 'hawks-3448f',
    authDomain: 'hawks-3448f.firebaseapp.com',
    storageBucket: 'hawks-3448f.firebasestorage.app',
  );
}
